### ISSUE TITLE
Call For Requests!!!

### ISSUE THREAD

**Issue by dsarfati** [OrleansContrib/OrleansDashboard#152]
We have 2 React interns that will be spending a month with our team and we are planning on having them work on the dashboard. I would like to get a list of ideas together so we can let them pick a few items to work while they are with us.

So far we have:
- Ability to drill down to a specific grain activation instead of just the grain type
- Sort/filter the grain table
- Call a grain method (similar to the swagger UI)
- Deactivate a specific grain activation
- Map/graph showing the connections between grains based on the method calls (possibly similar to the cosmosDB gremlin UI show below)
![graph](https://user-images.githubusercontent.com/7310169/40465855-b73846b8-5ed7-11e8-9f7e-b99b0c1bac34.png)

**Comment by richorama** [comment]
Thank you @dsarfati, this is an amazing offer!

Here's a shortlist for some of the UI related issues. Of course I'm open to more ideas.

* #135 
* #127 
* Consider (investigate) switching the JS build to webpack
* #57 & #51 (various improvements could be made to reminders)
* #26 
* #10
* #3 (sorting and filtering grain tables)
* General tidy up of the code

In terms of visualising grains in a graph, and understanding the behaviour of individual grains, I believe https://github.com/DerivcoIpswich/Orniscient does a good job of this.

I would be happy to have a skype chat to introduce how the dashboard works, if that would be helpful?

**Comment by ReubenBond** [comment]
Some random ideas for features/changes - mostly not UI issues
* .NET Runtime version
* Current total/available memory
* Environment variables
* Total set of known grain classes and interfaces on each silo
* Configuration object values
* Loaded assemblies, including paths & metadata (version, etc)
* Historic values / graphs for each counter
* Graph of communications between each grain (eg, by using incoming + outgoing call filters - maybe based on Orniscient)
* Ability to inspect each activation's internal state & persistent state

Maybe some of those are too sensitive to display, but I'd say it's up to the developer.

They can always ask for assistance with the Orleansy things in [gitter](https://gitter.im/dotnet/orleans)

**Comment by SebastianStehle** [comment]
Some ideas (will add more)

* Tracking of activation performance.
* Widgets and custom dashboards.

**Comment by jkonecki** [comment]
Change the architecture from pull to push - SignalR maybe?

**Comment by rikbosch** [comment]
An overview of exception rates and top X exceptions per silo / grain / method

**Comment by justmara** [comment]
Btw. Maybe use something like [AppMetrics](https://www.app-metrics.io/) for stat collection and counts? Current ConcurrentDictionary-based are very limited ;) And using appmetrics one could totally skip hosting dashboard itslef in orlean's host and simply translate metrics to something like InfluxDb or esle, using any dashboard he already uses, but with all the fine-grained metrics from this project.

**Comment by justmara** [comment]
@SebastianStehle I mean that this project can be pretty easily split into two:
1. collecting data (grain filters and sending metrics to ITelemetryProducer)
2. self-hosted metrics viewer: dashboard host itself and in-memory metrics collection.

First part would be useful when you have any external metrics tracking system and only want to get all the metrics this project provides without re-inventing the wheel and repeating'em, and without hosting cpu-intensive local metric collection in Silo process and bringing all the _garbage_ dependencies. Something like `RegisterMetricCollectors()` method, that only adds filters and metric _collection_ grains.
Sure I can write your custom filters but why must I do it while it is already have been made here? :)

Second part would be dashboard itself with all the dependencies needed - web host, local metrics collector etc. As for metrics collector I've mentioned AppMetrics because it is really fast flexible with really low cpu overhead but still powerful realtime metrics processing with mean/avg/percentile metrics. So looks like it could be used as local _storage_ instead of concurrentdictionaries.

**Comment by SebastianStehle** [comment]
100%, this is what I mean with my last sentence:

>Of course we could also restructure orleans and separate it into multiple packages/projects.

**Comment by richorama** [comment]
Hey @seniorquico, apologies, I've just got back from vacation. Happy to arrange a call on Monday, or any other day next week. I'm in the UK so if there's a time when we overlap our working day, that would be great.

**Comment by richorama** [comment]
awesome to hear you've got some people who can work on this BTW, very exciting.

**Comment by seniorquico** [comment]
Thanks, @richorama! Happy to find any time that works great for you. We're in the US Pacific time zone. You can reach me at kyle@zapic.com.

**Comment by SebastianStehle** [comment]
Can we close this task or create concrete issues?
