### ISSUE TITLE
allow users to define new views containing grain method invocation charts from multiple grain types

### ISSUE THREAD

**Issue by danvanderboom** [OrleansContrib/OrleansDashboard#28]
For analysis, showing correlations, connections, and cause-effect relationships visually among grains of different grain types.

**Comment by alexanderdevoid** [comment]
This would be very cool.

**Comment by danvanderboom** [comment]
I almost created a duplicate feature request, but since I provided so little information originally, I'll include my new write up here anyway:

Seeing all the activity across all the methods of a single grain type is great.

Going one step further, it would be nice to place specific methods from various grain types into a single, custom view and to save that (in a list of custom views) as a Testing Scenario, System Use Case Data Flow, etc.

This would make it easier to see all the activity for a data flow scenario on a single page. Currently, I do a lot of jumping between pages because the scenario I'm testing span activities (grain method calls) across numerous grain types. And sometimes a small number of grain methods out of many in each grain type are involved.

In one of many possible approaches, it would be nice to navigate among a list of standard and saved custom views in a list along the left, and see the corresponding charts on the remainder of the window on the right.

**Comment by carloslazo** [comment]
I'll be looking towards working on this specific enhancement soon and looking for more suggestions. Here is a summary of ideas: 

-  Place specific grain method charts from various grain-types into a single custom view.
-  Custom views can be named and saved into a list. 
- Able to rearrange grain method charts order in custom views.

**Comment by richorama** [comment]
@carloslazo sounds good to me. I have abstracted out the code that talks to localstorage into a 'storage' module. It will pollyfill if localstorage is missing. I recommend that you use this for persisting your view settings.

This may need a new menu entry. I wonder if there is a way we could make this flexible, and you were able to pick various counters to add there.

My only concern is that of performance in the C# world, and a way of retrieving the exact data you need. Happy to help with the design of this.

**Comment by carloslazo** [comment]
@richorama Kyle and I spoke more about this topic. Here are some of our thoughts. 

> I recommend that you use this for persisting your view settings.

Agree about storing client-side. This would keep integrating dashboard into projects simple, and wouldn't have to worry about state/persistence configuration (and implementation differences between storage types).

note, thinking the custom views could even be exported/imported to share across computers and/or with other users. But this idea is an aside for now. 

> My only concern is that of performance in the C# world, and a way of retrieving the exact data you need. Happy to help with the design of this.

First issue here is getting lots of unneeded data for Type.Method that isn't on your current graph. second issue could be too many HTTP requests for a single custom view if we needed to fetch each grain type + method as a separate call.

Even still, this sounds like a good starting point to get the UI built and functional:
As an example, this would result in polling every 1 second to all of the following API methods:

GET /GrainStats/TypeAGrain
GET /GrainStats/TypeBGrain
GET /GrainStats/TypeCGrain

Another proposal to improve this is by making an API method call like:

GET /GrainStats?Types=TypeAGrain.Method1,TypeBGrain.Method2,TypeCGrain.Method3

... potential issue here is a limit to the total number of grain types + methods in a single view due to URL length limits.

question: Do we want to set limits to the total number of call graphs per custom view?
