### ISSUE TITLE
How are the 'tags' implemented?

### ISSUE THREAD

**Issue by dandago** [OrleansContrib/OrleansDashboard#37]
Next to each grain type, the dashboard shows what look like tags, e.g. "System Grain" or "Dashboard Grain" (see [screenshot](http://gigi.nullneuron.net/gigilabs/wp-content/uploads/2017/03/orleans-dashboard-3.png)).

How do these work - is it actually possible to tag grains?

**Comment by richorama** [comment]
Hi @dandago, thanks for the question.

Because the orleans uses grains itself (as does the dashboard) these could confuse the user. Therefore they're marked with the tags, so you can tell they're not part of your solution.

At the moment you can't add your own tags, their just generated by the system by looking at the grain namespace. (i.e. if it starts `Orleans.*` then it's an Orleans grain).

If you would like to tag your own grains, we could look at doing that. Please feel free to raise this as an issue/PR :¬)
