### ISSUE TITLE
.Net Core Compatibility

### ISSUE THREAD

**Issue by creyke** [OrleansContrib/OrleansDashboard#41]
To discuss what it would take to make Dashboard compatible with .Net Core.

**Comment by galvesribeiro** [comment]
To make it work on both frameworks (full and core) the easiest way IMHO is to port the Dashboard to use Asp.Net Core which work on both frameworks. To add react in it, there is a new thing called JavaScriptServices. Just a bunch of boilerplate code that make the mix JS<>.Net easy (https://github.com/aspnet/JavaScriptServices).

**Comment by richorama** [comment]
The react part can probably remain unchanged, it's all rendered in the browser, and complied by node at build time. 

I agree with @galvesribeiro's suggestion about asp.net though. Would be nice to use kestrel.

**Comment by galvesribeiro** [comment]
AH, keep in mind that regardless of ASP.Net, the dashboard should conditionally (MSBuild condition reference) depends (for now) on Orleans stable release (from nuget.org) and TP release(from myget.org) so it can keep working on both versions of Orleans. Once 2.0 get released, you can get rid of the conditional reference and use only 2.0+ since it will support netstandard.

**Comment by richorama** [comment]
There is a `netstandard` [branch](https://github.com/OrleansContrib/OrleansDashboard/tree/netstandard) which I managed to get to compile for the dashboard proj. I couldn't figure out how to get the test host executable to work though.

The branch is now a long way behind, so it might be easier to just start again, given the the tooling and frameworks have moved on since then.

I'm quite inexperienced in .NET core, so any help here would be appreciated. I don't think it's a huge job, most of the code is JavaScript, which won't be affected.

**Comment by creyke** [comment]
The code is now compatible with .net core via [this PR](https://github.com/OrleansContrib/OrleansDashboard/pull/67) but has separate .sln and .csproj files.

I don't think I'm the best person to tie this into the build and release process for this project... maybe someone familiar with the existing .net framework one could pick this piece up?
