### ISSUE TITLE
Disable Log Stream View

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/OrleansDashboard#78]
Is it possible to disable the log stream view.

As far as I understand it, it shows the log of the current Silo only, therefore it is misleading in a multi-node environment.

**Comment by richorama** [comment]
Correct. Due to technical limitations it's impractical to bring back log data from all silos. The log does write out the name of the silo which is the source of the log, but perhaps it could be more explicit about this.

It's not currently possible to disable the log stream, but it wouldn't be too difficult to add this feature.

**Comment by SebastianStehle** [comment]
I am not sure, if this is still possible with Orleans 2.0 ... because the logging is now part of the DI system and you do not have the same control. e.g. I have replaced the whole logger ;)

**Comment by SebastianStehle** [comment]
Solved in the 2.0 Branch
